services:
  frontend:
    develop:
      watch:
        - action: sync
          path: ./app
          target: /src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    build: ./frontend
    ports:
      - '8081:8081'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_TOKEN=${EXPO_TOKEN}
    command: ['npx', 'expo', 'start']
